services:
  - type: web
    name: groupe-omega-site
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn identity_digitale.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 60
    healthCheckPath: /
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
